# 上課筆記

In [1]:
import numpy as np

In [2]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [3]:
rng = np.random.default_rng(seed=1234)
n=1000

In [4]:
##Setup model
X = np.hstack([
    np.ones((n,1)),
    rng.random((n,5))
])
beta = np.array([7,-3.3,2.4,1.5,9.7,-10])
err = rng.normal(0,0.1,size = n)
y = X @ beta + err
y

array([ 5.29941601e+00,  1.42593120e+01,  1.02095449e+01, -5.89178553e-02,
        1.46724898e+01,  2.94359103e+00,  1.36848025e+01,  1.68618708e+00,
        7.34565072e+00,  5.79584771e+00,  1.10079660e+00,  5.15417586e+00,
        1.71935884e+01,  6.31824919e+00,  3.14261527e+00,  9.55373940e+00,
        9.65401516e-02,  1.00046897e+01,  7.52708464e-01,  1.47520660e+01,
        4.71830724e+00,  9.31395945e+00,  1.59669609e+01, -9.52264531e-01,
        1.35870476e+00,  6.94092730e+00,  1.18678653e+01,  8.00718691e-01,
        7.96413940e+00,  5.48541269e+00,  6.36052621e+00,  6.25015576e+00,
        1.02970413e+00,  6.72546565e+00,  4.26405550e+00,  1.34256914e+01,
        1.55271237e+01,  6.64721681e+00,  5.87952241e+00,  1.44521633e+01,
        1.29911338e+01,  9.46960615e+00, -2.60255143e+00,  1.54774681e+01,
        1.50064105e+01,  1.26693008e+01,  1.48186193e+01,  7.58342885e+00,
        8.42339144e+00,  5.22305314e+00,  1.12415756e+01,  1.68276816e+01,
        4.22294681e+00,  

In [5]:
##fit model

beta_hat = np.linalg.inv(X.T @ X) @ X.T @ y
print (beta_hat)
print (beta)

[  6.99605754  -3.2816873    2.37891499   1.511036     9.70649269
 -10.00185516]
[  7.   -3.3   2.4   1.5   9.7 -10. ]


## 輸出部分Array

In [7]:
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
#subsect to get the 2x2 with 5,6,9,10 as elements

x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [10]:
x[[1,2],[1,2]]

array([ 5, 10])

In [11]:
x[[1,2],][:,[1,2]]

array([[ 5,  6],
       [ 9, 10]])

In [12]:
x[[3,3,3,0],]

array([[12, 13, 14, 15],
       [12, 13, 14, 15],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [ ]:
S