## Exercise 1

In [15]:
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
import numpy as np

In [32]:
#subset to get the 2x2 with 5,6,9,10

print(x[1:3,1:3])
#or
print(x[[1,2],][:,[1,2]])

[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]


## Exercise 2

We will now use this to attempt a simple brute force approach to numerical optimization, define a grid of points using meshgrid() to approximate the minima the following function:

$$f(x,y)=(1-x)^2+100 (y-x^2)^2$$

Considering values of $x, y \in (-1,3)$, which values of $x, y$ minimize this function?

In [42]:
x,y = np.meshgrid(np.arange(-1,3),np.arange(-1,3))

print(x)

print(y)

[[-1  0  1  2]
 [-1  0  1  2]
 [-1  0  1  2]
 [-1  0  1  2]]
[[-1 -1 -1 -1]
 [ 0  0  0  0]
 [ 1  1  1  1]
 [ 2  2  2  2]]


In [47]:
pow((1-x),2)+100*pow((y-pow(x,2)),2)

array([[ 404,  101,  400, 2501],
       [ 104,    1,  100, 1601],
       [   4,  101,    0,  901],
       [ 104,  401,  100,  401]])